name: Windows

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  Windows:
    env:
      FILENAME: 0

    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install and Setup Dependencies 
      run: |
        Invoke-WebRequest -Uri "https://www.libsdl.org/release/SDL2-devel-2.0.12-mingw.tar.gz" -OutFile "sdl2.tar.gz"
        7z x -y "sdl2.tar.gz" -so | 7z x -y -aoa -si -ttar "-oC:\tools\

    - name: Compile
      run: |
        cd example/
        mkdir build
        cd build
        ls c:/tools/
        cmake .. -DSDL2_PATH="C:/tools/SDL2-2.0.12" -G "MinGW Makefiles"
        cmake --build .

    # Only create artifact on a push to master
    # - if: github.event_name == 'push' 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.FILENAME }}
        path: |
          lvgl_example.exe
