name: Windows

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2

    - name: Install and Setup Dependencies 
      run: |
        pacman -S mingw-w64-x86_64-make --noconfirm
        pacman -S mingw-w64-x86_64-cmake --noconfirm
        pacman -S mingw-w64-x86_64-gcc --noconfirm
        pacman -S mingw-w64-x86_64-SDL2 --noconfirm

    - name: Compile
      run: |
        cd example/
        mkdir build
        cd build
        cp C:/msys64/mingw64/bin/SDL2.dll SDL2.dll
        cmake .. -G "MinGW Makefiles"
        cmake --build .
        ls

    # Only create artifact on a push to master
    - if: github.event_name == 'push' 
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lvgl_example_winx86_64
        path: |
          example/build/lvgl_example.exe
          example/build/SDL2.dll
