name: Xbox

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install and Setup Dependencies
      run: |
        sudo apt-get update -y && sudo apt-get install -y flex bison clang lld
        git clone https://github.com/XboxDev/nxdk.git --recursive
        ls /usr/lib/
        export PATH=$PATH:/usr/lib/llvm-6.0/bin

    - name: Compile
      run: |
        cd example/
        make -f Makefile.nxdk NXDK_DIR=~/nxdk

    # Only create artifact on a push to master
    - if: github.event_name == 'push' 
      name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lvgl_example_ogxbox
        path: |
          example/lvgl_example.iso
          example/default.xbe
